# training config
global_config:
    seed: 1234
    

# model_config
model_config:
    rbf: nexpnorm
    max_z: 20
    rbf_trainable: false
    rbound_upper: 10
    z_hidden_dim: 256
    ef_dim: 72
    k_tuple_dim: 256
    block_num: 5
    activation_fn_name: ssp
    interaction_residual: false
    use_mult_lin: true
#lr0.0001