train:
  batch_size: 16
  eval_batch_size: 32
  seed: 2021
  epochs: 400  
  shuffle: true
  resume_train: false
  eval: true
  num_workers: 5
  gpus:
    - 0
    - null
    - null
    - null
  anneal_power: 2.0
  save: true
  save_path: root/to/save_3_blocks_2_lr
  resume_checkpoint: null
  resume_epoch: 0
  log_interval: 400
  optimizer:
    type: Adam
    lr: 0.0002
    weight_decay: 0.0000
    dropout: 0.0
  scheduler:
    type: plateau
    factor: 0.6
    patience: 20
    min_lr: 5e-5 
  loss:
    position: 1
    distance: 0
    curl: 0
  wandb:
    Enable: True
    Project: Molecular-Generation
  Name: clofnet4qm9


test:
  init_checkpoint: root/to/save_3_blocks_2_lr
  output_path: root/to/generation_3_blocks_2_lr
  gen:
    steps_pos: 100
    step_lr_pos: 0.000002
    clip: 1000
    min_sigma: 0.0
    verbose: 1
    repeat: 2


data:
  base_path: root/to/dataset
  dataset: qm9
  train_set: train_data_40k.pkl
  val_set: val_data_5k.pkl
  test_set: test_data_200.pkl


model:
  hidden_dim: 288
  num_convs: 4
  sigma_begin: 10
  sigma_end: 0.01
  num_noise_level: 50
  order: 3
  mlp_act: relu
  gnn_act: relu
  cutoff: 10.0
  short_cut: true
  concat_hidden: false   
  noise_type: rand
  edge_encoder: mlp